### PR TITLE
Making quickstart code compatible with Python 3.6

### PR DESCRIPTION
**Pull request by Kevxn**
Figured I would create a pull request for #99 that I created.

I'm not sure if this is the direction to go in, or if it would be better to support Python 3.7+ or to include examples for both Python 3.6 and 3.7, but it was just a small change anyway.

### CODE REVIEW

**Comment by amosbastian** [comment]
Thanks! I didn't realise it wasn't compatible with Python 3.6 🤦 

Maybe it's better to just replace all 

```
asyncio.run(main())
```

with

```
# Python >= 3.7
asyncio.run(main())
# Python 3.6
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

What do you think?

**Comment by Kevxn** [comment]
Yeah that could be a solution. I'd be happy to go through the docs and make the changes.

Is there anywhere else I would need to make changes?

**Comment by amosbastian** [comment]
> Yeah that could be a solution. I'd be happy to go through the docs and make the changes.
> 
> Is there anywhere else I would need to make changes?
> 
> **edit**
> I realised that the 3.6 code is compatible with newer versions too, so could change everything to:
> 
> ```
> loop = asyncio.get_event_loop()
> loop.run_until_complete(main())
> ```

If you want to do it then go ahead (it's boring work 😛), otherwise I can do it too! And you are right about it being compatible with the newer versions, but I think it makes sense to let users know that they can also use 1 line instead of 2 if they are using >= 3.7, but up to you.

**Comment by Kevxn** [comment]
I'd be happy to make make the changes :) I will try and get around to it sometime this week

**Comment by Kevxn** [comment]
> I'd be happy to make make the changes :) I will try and get around to it sometime this week

Sorry, I was pretty busy at work last week. How would this work for the examples?

    if __name__ == '__main__':
        if sys.version_info >= (3, 7):
            asyncio.run(main())
        else:
            loop = asyncio.get_event_loop()
            loop.run_until_complete(main())


I've tested this on my machine with Python 3.6 and 3.7, and it's working fine.

**Comment by amosbastian** [comment]
Sorry, completely forgot to reply 😅 just request a review from me when it's done and I will check it out once it's done. Thanks again! 😻

**Comment by Kevxn** [comment]
> Sorry, completely forgot to reply 😅 just request a review from me when it's done and I will check it out once it's done. Thanks again! 😻

I don't see the option to request a review, but I think it should be good to go. Assuming I've not missed anything, or you'd prefer a different format.

**Pull request merged**
