### PR TITLE
dict_return_types

### PR DESCRIPTION
**Pull request by johnmadden86**
return id indexed dicts for fixtures, teams, players etc

### CODE REVIEW

**Comment by amosbastian** [comment]
I don't really agree with creating indexed dictionaries like this. It doesn't have any benefit over lists as far as I'm aware of and for example it makes it more cumbersome to search for a player by their name and team. Also creates an inconsistency of what you expect to be returned from the API and what is actually returned (setting `return_json=True/False`).

**Comment by johnmadden86** [comment]
The advantage is that data can be accessed like a list - player[index],
fixture[index] - but the indexes are the player ids instead of list indexes
which are just the order they come in.
So no iteration is necessary to select the one you want.
Rescheduled fixtures will have the same id but appear in a different order.
The range of player ids is more than the number of players in the game
because of transfers out.
It's convenient for adding future methods.
I think your get all gameweeks method had this return type already

**Comment by amosbastian** [comment]
You still need to iterate over the dictionary's keys to get multiple entries and it's less convenient when searching for players when not using their ID. For efficiency I really doubt it makes any or much difference, but I could be wrong.

>Rescheduled fixtures will have the same id but appear in a different order.

I don't really understand what you mean by this. Could you elaborate?

>The range of player ids is more than the number of players in the game because of transfers out.

I know, but I don't really see why this matters. Could you explain this as well?

>It's convenient for adding future methods.

How so?

>I think your get all gameweeks method had this return type already

I can vaguely remember this but I think I changed it back to a list because I realised it wasn't the best thing to do and for it to give more consistency between the package and the actual API.

Either way, doing this will also break the code of everyone who has code that iterates over the returned lists if they decide to upgrade the package.

**Comment by johnmadden86** [comment]
> You still need to iterate over the dictionary's keys to get multiple entries and it's less convenient when searching for players when not using their ID. For efficiency I really doubt it makes any or much difference, but I could be wrong.

Can use the filter function for this

> > Rescheduled fixtures will have the same id but appear in a different order.
> 
> I don't really understand what you mean by this. Could you elaborate?
e.g. Liverpool v West Ham, was due for GW 18 id 180.
Won't be played until later.
Can access this fixture by fixtures[180] instead of need an iteration

Similarly players[215] gets Kevin de Bruyne, no need for iteration.
It's useful for getting and setting the live_score attribute I want to implement

So if I want to get my team's live total, the /picks endpoint will just give me the player ids
I need to get the live scores from the Player class
I think it's convenient not to need to set up an iteration every time

**Comment by amosbastian** [comment]
I see. I think the problem with backwards compatibility still remains as it will break a lot of my own code that expects a list to be returned for example. If you can find a solution for that I don't mind it being added.

**Comment by johnmadden86** [comment]
I understand it's quite a fundamental change but I do think it's better
I don't think it's something I can find a workaround for or that can be compromised on, just need to pick a style and stick with it.
It's easy to get a list from the dict_values when needed, easier than performing an iteration to find an item in my opinion

**Pull request closed without merging**
