### PR TITLE
h2h league get fixtures fix

### PR DESCRIPTION
**Pull request by johnmadden86**
Very much a newbie to programming and haven't contributed to a project like this before so hope I've done this right!

### CODE REVIEW

**Comment by amosbastian** [comment]
Great work! I personally don't participate in any H2H leagues so it's really nice to have other people come and fix stuff.

**Comment by johnmadden86** [comment]
Thanks! Appreciate the feedback.
Nice to do something more real than just playground type college work.
Hope I can keep contributing.

**Comment by amosbastian** [comment]
Btw I changed some small things in [this commit](https://github.com/amosbastian/fpl/pull/52/commits/267c12a709c8f103f8af703d112be8d95baa0bd3) if you are interested in learning some more.

**Comment by johnmadden86** [comment]
I thought about making the page a parameter, but decided it was confusing
as it was hard to see when or why someone would want that.
For my own h2h league (10 people) there are fixtures made for 36 gameweeks,
each page gives 10 gameweeks of fixtures (apart from the last one,
obviously).
But It might be different for larger leagues.
I'd consider changing the name of the parameter to start_page, as it
returns all pages from there.

**Comment by amosbastian** [comment]
O I see, then I agree and it doesn't make sense to have it as an argument. I'll change it when I update to version 0.6.15 :+1:

**Pull request merged**
